language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"

env:
  - VER=min
  - VER=req
  - VER=

install:
  - if [ -n "$VER" ]; then pip install -r $VER*.txt; fi
  - pip install -r requirements/development.txt

script:
  - make mo test build SHELL=/bin/bash TAIL='|tail -40; exit $$PIPESTATUS'

after_success:
  - coveralls
